// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type SearchRequest struct {
	OrderId int `json:"orderId"`
}

type SearchResponse struct {
	OrderId  int64 `json:"orderId"`
	Status   int `json:"status"`
	Username string `json:"username"`
}
