// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"mall/service/shortener/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/shortener/:shortUrl",
				Handler: ShortHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/shortener/convert",
				Handler: ConvertHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
