// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package user

import (
	"context"

	"mall/service/system/rpc/types/system"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserDetailsRequest  = system.GetUserDetailsRequest
	GetUserDetailsResponse = system.GetUserDetailsResponse

	User interface {
		GetUserDetail(ctx context.Context, in *GetUserDetailsRequest, opts ...grpc.CallOption) (*GetUserDetailsResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUserDetail(ctx context.Context, in *GetUserDetailsRequest, opts ...grpc.CallOption) (*GetUserDetailsResponse, error) {
	client := system.NewUserClient(m.cli.Conn())
	return client.GetUserDetail(ctx, in, opts...)
}
