// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	roleFieldNames          = builder.RawFieldNames(&Role{})
	roleRows                = strings.Join(roleFieldNames, ",")
	roleRowsExpectAutoSet   = strings.Join(stringx.Remove(roleFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	roleRowsWithPlaceHolder = strings.Join(stringx.Remove(roleFieldNames, "`role_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoZeroRoleRoleIdPrefix = "cache:goZero:role:roleId:"
)

type (
	roleModel interface {
		Insert(ctx context.Context, data *Role) (sql.Result, error)
		FindOne(ctx context.Context, roleId string) (*Role, error)
		Update(ctx context.Context, data *Role) error
		Delete(ctx context.Context, roleId string) error
	}

	defaultRoleModel struct {
		sqlc.CachedConn
		table string
	}

	Role struct {
		RoleId    string    `db:"role_id"`
		Name      string    `db:"name"`
		Code      string    `db:"code"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
		IsDeleted uint64    `db:"is_deleted"`
	}
)

func newRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultRoleModel {
	return &defaultRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`role`",
	}
}

func (m *defaultRoleModel) Delete(ctx context.Context, roleId string) error {
	goZeroRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroRoleRoleIdPrefix, roleId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `role_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, roleId)
	}, goZeroRoleRoleIdKey)
	return err
}

func (m *defaultRoleModel) FindOne(ctx context.Context, roleId string) (*Role, error) {
	goZeroRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroRoleRoleIdPrefix, roleId)
	var resp Role
	err := m.QueryRowCtx(ctx, &resp, goZeroRoleRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `role_id` = ? limit 1", roleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, roleId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRoleModel) Insert(ctx context.Context, data *Role) (sql.Result, error) {
	goZeroRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroRoleRoleIdPrefix, data.RoleId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, roleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoleId, data.Name, data.Code, data.IsDeleted)
	}, goZeroRoleRoleIdKey)
	return ret, err
}

func (m *defaultRoleModel) Update(ctx context.Context, data *Role) error {
	goZeroRoleRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroRoleRoleIdPrefix, data.RoleId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `role_id` = ?", m.table, roleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Code, data.IsDeleted, data.RoleId)
	}, goZeroRoleRoleIdKey)
	return err
}

func (m *defaultRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoZeroRoleRoleIdPrefix, primary)
}

func (m *defaultRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `role_id` = ? limit 1", roleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRoleModel) tableName() string {
	return m.table
}
