// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userRelationRoleFieldNames          = builder.RawFieldNames(&UserRelationRole{})
	userRelationRoleRows                = strings.Join(userRelationRoleFieldNames, ",")
	userRelationRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(userRelationRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRelationRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(userRelationRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoZeroUserRelationRoleIdPrefix = "cache:goZero:userRelationRole:id:"
)

type (
	userRelationRoleModel interface {
		Insert(ctx context.Context, data *UserRelationRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserRelationRole, error)
		Update(ctx context.Context, data *UserRelationRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserRelationRoleModel struct {
		sqlc.CachedConn
		table string
	}

	UserRelationRole struct {
		Id     int64  `db:"id"`
		UserId string `db:"user_id"` // 用户ID
		RoleId string `db:"role_id"` // 角色ID
	}
)

func newUserRelationRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserRelationRoleModel {
	return &defaultUserRelationRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_relation_role`",
	}
}

func (m *defaultUserRelationRoleModel) Delete(ctx context.Context, id int64) error {
	goZeroUserRelationRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserRelationRoleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goZeroUserRelationRoleIdKey)
	return err
}

func (m *defaultUserRelationRoleModel) FindOne(ctx context.Context, id int64) (*UserRelationRole, error) {
	goZeroUserRelationRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserRelationRoleIdPrefix, id)
	var resp UserRelationRole
	err := m.QueryRowCtx(ctx, &resp, goZeroUserRelationRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRelationRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserRelationRoleModel) Insert(ctx context.Context, data *UserRelationRole) (sql.Result, error) {
	goZeroUserRelationRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserRelationRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userRelationRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	}, goZeroUserRelationRoleIdKey)
	return ret, err
}

func (m *defaultUserRelationRoleModel) Update(ctx context.Context, data *UserRelationRole) error {
	goZeroUserRelationRoleIdKey := fmt.Sprintf("%s%v", cacheGoZeroUserRelationRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRelationRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.RoleId, data.Id)
	}, goZeroUserRelationRoleIdKey)
	return err
}

func (m *defaultUserRelationRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoZeroUserRelationRoleIdPrefix, primary)
}

func (m *defaultUserRelationRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRelationRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserRelationRoleModel) tableName() string {
	return m.table
}
