// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: user.proto

package server

import (
	"context"

	"mall/service/system/rpc/internal/logic"
	"mall/service/system/rpc/internal/svc"
	"mall/service/system/rpc/types/system"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUserDetail(ctx context.Context, in *system.GetUserDetailsRequest) (*system.GetUserDetailsResponse, error) {
	l := logic.NewGetUserDetailLogic(ctx, s.svcCtx)
	return l.GetUserDetail(in)
}
