// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ConvertRequest struct {
	LongUrl string `json:"longUrl" validate:"required"`
}

type ConvertResponse struct {
	ShortUrl string `json:"shortUrl"`
}

type ShortRequest struct {
	ShortUrl string `json:"shortUrl" validate:"required"`
}

type ShortResponse struct {
	LongUrl string `json:"longUrl"`
}
