// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Button struct {
	ButtonId string `json:"buttonId"`
	Name     string `json:"name"`
	Code     string `json:"code"`
}

type Menu struct {
	MenuId   string `json:"menuId"`
	Name     string `json:"name"`
	Code     string `json:"code"`
	Path     string `json:"path"`
	Serial   string `json:"serial"`
	ParentId string `json:"parentId"`
}

type Role struct {
	RoleId string `json:"roleId"`
	Name   string `json:"name"`
	Code   string `json:"code"`
}

type LoginRequest struct {
	UserName string `json:"username,default=Sutter"`
	Password string `json:"password,default=1234@Abcd"`
}

type LoginResponse struct {
	Message      string   `json:"message"`
	AccessToken  string   `json:"accessToken"`
	AccessExpire int      `json:"accessExpire"`
	RefreshAfter int      `json:"refreshAfter"`
	Roles        []Role   `json:"roles"`
	Menus        []Menu   `json:"menus"`
	Buttons      []Button `json:"buttons"`
}

type RegisterRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Message string `json:"message"`
}

type RoleSearchRequest struct {
	Keyword string `json:"keyword"`
}

type RoleSearchResponse struct {
	Message string `json:"message"`
}
