// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Message      string `json:"message"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int    `json:"accessExpire"`
	RefreshAfter int    `json:"refreshAfter"`
}

type SignupRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
	Gender   int    `json:"gender",options=0|1|2, default=0`
}

type SignupResponse struct {
	Message string `json:"message"`
}

type UserDetailsRequest struct {
	UserId int64 `json:"userId"`
}

type UserDetailsResponse struct {
	UserId   int64  `json:"userId"`
	UserName string `json:"username"`
	Gender   int    `json:"gender"`
	Email    string `json:"email"`
}
