// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type SignupRequest struct {
	UserName string `json:"username"`
	Password string `json:"password"`
	Gender   string `json:"gender",options=male|female|Unknow`
}

type SignupResponse struct {
	Message string `json:"message"`
}
